operation: |
    mutation {
        t1: createDocument(data: {
            name: "Document 1",
            file: {
                name: "document-1.pdf",
                date: "2021-07-06T20:08:47",
                url: "http://local.url/document-1.pdf"
            }
        }) {
            id @bind(name: "t1id")
        }
    }
